export default {
  splashLogo: require('../assets/images/splash-cheeck.png'),
  logo: require('../assets/images/logo-cheeck.png'),
  head: require('../assets/images/profileHead-cheeck.png'),
  imageHead: require('../assets/images/imageHead-cheeck.png'),
  menuCards: require('../assets/images/cards-cheeck.png'),
  menuCardsOn: require('../assets/images/cardsOn-cheeck.png'),
  menuPlaces: require('../assets/images/places-cheeck.png'),
  menuPlacesOn: require('../assets/images/placesOn-cheeck.png'),
  menuRead: require('../assets/images/readcode-cheeck.png'),
  menuAwards: require('../assets/images/awards-cheeck.png'),
  menuAwardsOn: require('../assets/images/awardsOn-cheeck.png'),
  menuConfiguration: require('../assets/images/configuration-cheeck.png'),
  menuConfigurationOn: require('../assets/images/configurationOn-cheeck.png'),
  trophy: require('../assets/images/trophy-cheeck.png'),
  mapsLocal: require('../assets/images/maps-cheeck.png'),
  loading: require('../assets/images/loading-cheeck.gif'),
  abraselLogo: require('../assets/images/abrasel-cheeck.png'),
};
